# Generated by Django 3.1.1 on 2020-10-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='author_profiles')),
                ('author_image_link', models.URLField(blank=True, null=True)),
                ('alt_msg', models.CharField(default="Author's Profile picture", max_length=100)),
            ],
        ),
    ]
