# Generated by Django 3.1.1 on 2020-10-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='author_image_link',
            new_name='profile_image_link',
        ),
    ]
