# Generated by Django 3.1.2 on 2020-10-25 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('tags', '0002_tags_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(max_length=5000)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('image_link', models.URLField(blank=True, null=True)),
                ('alt_msg', models.CharField(default='Image related to this blog', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='authors.authors')),
                ('tags', models.ManyToManyField(related_name='blogs', to='tags.Tags')),
            ],
        ),
    ]
