# Generated by Django 3.1.1 on 2020-10-03 13:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('blog_title', models.CharField(max_length=300)),
                ('blog_content', models.TextField(default='This is some detailed content about the blog', max_length=5000)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('blog_image_link', models.URLField(blank=True, null=True)),
                ('alt_msg', models.CharField(default='Image related to this blog', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='authors.authors')),
            ],
        ),
    ]
