# Generated by Django 3.1.1 on 2020-10-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20201008_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='blog',
        ),
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(to='blogs.Tags'),
        ),
    ]
