# Generated by Django 3.1.1 on 2020-10-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20201009_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='blogs.Tags'),
        ),
    ]
