# Generated by Django 3.1.1 on 2020-10-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('blogs', '0005_auto_20201009_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='tags.Tags'),
        ),
    ]
