# Generated by Django 3.1.1 on 2020-10-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
